In [ ]:
import dgl 
import torch

# basics of creating the graph

In [3]:
u, v = torch.tensor([0, 0, 0, 1]), torch.tensor([1, 2, 3, 3])

In [5]:
g = dgl.graph((u, v))

In [6]:
print(g)

Graph(num_nodes=4, num_edges=4,
      ndata_schemes={}
      edata_schemes={})


In [16]:
#node IDs
g.nodes()
#edge end nodes 
g.edges()

(tensor([0, 0, 0, 1]), tensor([1, 2, 3, 3]))

In [12]:
# edge end nodes and edge ids
g.edges(form='all')

(tensor([0, 0, 0, 1]), tensor([1, 2, 3, 3]), tensor([0, 1, 2, 3]))

In [13]:
g = dgl.graph((u, v), num_nodes=8)

In [15]:
#undirected graph 
bg = dgl.to_bidirected(g)
bg.edges()

(tensor([0, 0, 0, 1, 1, 2, 3, 3]), tensor([1, 2, 3, 0, 3, 0, 0, 1]))

In [17]:
edges = torch.tensor([2, 4, 3]), torch.tensor([4, 5, 0])

g = dgl.graph(edges)

In [19]:
g.nodes()

g.edges()

(tensor([2, 4, 3]), tensor([4, 5, 0]))

In [20]:
# dgl uses int64 by default, but using int32 instead
g32 = dgl.graph(edges, idtype=torch.int32)

In [21]:
g32

Graph(num_nodes=6, num_edges=3,
      ndata_schemes={}
      edata_schemes={})

# node and edge features 

In [38]:
g = dgl.graph((torch.tensor([0, 0, 0, 1]), torch.tensor([1, 2, 3, 3])))
g

Graph(num_nodes=4, num_edges=4,
      ndata_schemes={}
      edata_schemes={})

In [28]:
# adding node and edge features 
g.ndata['x'] = torch.ones(g.num_nodes(), 3)
g.edata['x'] = torch.ones(g.num_nodes(), dtype=torch.int32)
g.ndata['y'] = torch.randn(g.num_nodes(), 5)

In [36]:
g.edges()

(tensor([0, 0, 0, 1]), tensor([1, 2, 3, 3]))

# DGLGraph on GPU 

In [45]:
u, v = torch.tensor([0, 1, 2]), torch.tensor([2, 3, 4])
g = dgl.graph((u, v))

g.ndata['x'] = torch.randn(5, 5)
# send graph to device
device = 'cuda' if torch.cuda.is_available() else 'cpu'
cuda_g = g.to(device)

In [52]:
cuda_g.in_edges([4])

(tensor([2]), tensor([4]))

# message functions 

In [53]:
g

Graph(num_nodes=5, num_edges=3,
      ndata_schemes={'x': Scheme(shape=(5,), dtype=torch.float32)}
      edata_schemes={})

In [55]:
edges = g.edges()

In [60]:
def edge_udf(edges):
    return {'dst': edges.dst['x']}

In [61]:
g.apply_edges(edge_udf)
g.edata['dst']

tensor([[ 0.8223, -0.4124,  1.1526, -0.5104, -0.0501],
        [-0.1202, -0.5681,  0.0901, -0.9343, -0.7079],
        [ 0.4044, -0.4100, -1.3802, -0.5037,  1.1254]])

In [10]:
test=slice(1, 20, 2)

In [12]:
import numpy as np
np.arange(test.start, test.stop, test.step)

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])